"""
Django settings for einvoiceProject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os
import random, string

from pathlib import Path

from filebrowser.sites import site
site.directory = "uploads/"

import messages
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# env = environ.Env(DEBUG=(bool, False))
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Add .env variables anywhere before SECRET_KEY
# SECRET_KEY = env('SECRET_KEY')   # instead of my secret key
SECRET_KEY = 'django-insecure-*1(u(7m-)be_c(u@7ul-lxw8^zuv)9hk-$#s7*&_en231a_cum'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

# ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

ALLOWED_HOSTS = ['eiv.edvin.co', 'www.eiv.edvin.co',]
# ALLOWED_HOSTS = ['localhost','127.0.0.1','eiv.edvin.co', '152.53.248.137',]

    # ALLOWED_HOSTS = ['<prod DNS, host, and/or IP>',]
# else:
#     ALLOWED_HOSTS = ['localhost','127.0.0.1',]

# CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')
# CSRF_TRUSTED_ORIGINS=['https://127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'einvoice.apps.EinvoiceConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
    # 'django-bootstrap5'
    'bootstrap_datepicker_plus',
    'widget_tweaks',
]

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'einvoiceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
      ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
                # 'einvoice.context_processors.invoices_to_base',
                # 'companies.context_processors.get_enterprise_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'einvoiceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# if IS_LOCAL_APP:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'einvoice_db',     #schema
        'USER': 'root',
        'PASSWORD': 'Pages636!',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': env('DB_ENGINE'),
#         'NAME': env('DB_NAME'),
#         'USER': env('DB_USER'),
#         'PASSWORD': env('DB_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env('DB_PORT'),
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de-de'

# TIME_ZONE = 'Europe/Berlin'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [BASE_DIR / 'static',]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


LOGIN_REDIRECT_URL = '/einvoice/'
LOGOUT_REDIRECT_URL = '/'

# SECURE_SSL_REDIRECT = True  # 27.4.2026

EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'smtp.strato.de'
EMAIL_HOST_USER = 'send@rauner.de'
EMAIL_HOST_PASSWORD = '02226515SendTrue!'
EMAIL_PORT = 465
EMAIL_USE_SSL = True

SESSION_COOKIE_AGE = 28800  # 8 hours in seconds

BOOTSTRAP_DATEPICKER_PLUS = {
    "options": {
        "locale": "de",
    },
    "variant_options": {
        "date": {
            "format": "DD.MM.YYYY",
            "showTodayButton": True,
        },
        "time":{
            "format": "HH:mm",
        },
        # "datetime":{
        #      "format": "DD.MM.YYYY hh:mm",
        # },
    }
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
